version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - naruto_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - naruto_network

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - naruto_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  naruto_network: