# Generated by Django 5.2.4 on 2025-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jutsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='O nome único do jutsu.', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Uma descrição detalhada do jutsu, seus efeitos e como é executado.')),
                ('element_type', models.CharField(choices=[('fire', 'Fogo'), ('water', 'Água'), ('wind', 'Vento'), ('earth', 'Terra'), ('lightning', 'Raio'), ('illusion', 'Genjutsu'), ('yin', 'Yin'), ('yang', 'Yang'), ('yin-yang', 'Yin-Yang'), ('other', 'Outro')], default='other', help_text='O elemento de chakra principal do jutsu.', max_length=20)),
                ('jutsu_type', models.CharField(choices=[('offensive', 'Ofensivo'), ('defensive', 'Defensivo'), ('support', 'Suporte'), ('supplementary', 'Suplementar')], default='supplementary', help_text='A classificação funcional do jutsu.', max_length=20)),
                ('rank', models.CharField(choices=[('E', 'Rank E'), ('D', 'Rank D'), ('C', 'Rank C'), ('B', 'Rank B'), ('A', 'Rank A'), ('S', 'Rank S'), ('SS', 'Rank S+')], default='C', help_text='A classificação de dificuldade do jutsu.', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o jutsu foi registrado no catálogo.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro.')),
            ],
            options={
                'verbose_name': 'Jutsu',
                'verbose_name_plural': 'Jutsus',
                'ordering': ['name'],
            },
        ),
    ]
