# Generated by Django 5.2.4 on 2025-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jutsu',
            name='image',
            field=models.ImageField(blank=True, help_text='Uma imagem representativa do jutsu.', null=True, upload_to='jutsu_images/'),
        ),
    ]
